import Link from 'next/link';
import { services } from '@/data/site';

export default function Home(){return <>
<section className="hero"><div className="eyebrow">Electrical • Renewable Energy • Telecom</div><h1>Powering Business.<br/>Engineered for Reliability.</h1><p>Mitra untuk solusi Electrical, Renewable Energy & Telecom bagi bisnis, industri, commercial, infrastructure dan hunian.</p><Link className="btn" href="/kontak/">Konsultasikan Proyek ↗</Link></section>
<section className="section"><div className="sectionHead"><div className="eyebrow">Our Services</div><h2>Solusi teknis yang terintegrasi.</h2><p className="muted">JPN menyediakan layanan teknis yang dapat disesuaikan dengan kebutuhan proyek dan operasional customer.</p></div><div className="grid">{services.slice(0,3).map(s=><Link className="card" href={`/layanan/${s.slug}/`} key={s.slug}><img className="visual" src={s.visual} alt={s.title}/><h3>{s.title}</h3><p className="muted">{s.description}</p><b>Lihat layanan →</b></Link>)}</div></section>
<section className="section" style={{background:'#f7f9fc'}}><div className="sectionHead"><div className="eyebrow">Why JPN</div><h2>Engineering solutions you can rely on.</h2></div><div className="grid">{[['Reliable Engineering','Solusi teknis dengan pendekatan pengerjaan profesional.'],['Integrated Solutions','Electrical, Renewable Energy dan Telecom dalam satu partner.'],['Professional Execution','Perencanaan, pelaksanaan, keselamatan dan kualitas menjadi bagian dari proses.']].map(x=><div className="card" key={x[0]}><h3>{x[0]}</h3><p className="muted">{x[1]}</p></div>)}</div></section>
<section className="section"><div className="sectionHead"><div className="eyebrow">Projects</div><h2>Project portfolio akan dibangun dari data aktual.</h2><p className="muted">Kami tidak menampilkan project fiktif. Setelah data dan foto project JPN tersedia, setiap project akan memiliki halaman detail, gallery, scope dan related services.</p></div><Link className="btn" href="/proyek/">Lihat Portfolio</Link></section>
<section className="section" style={{background:'#071526',color:'#fff'}}><div className="sectionHead"><div className="eyebrow">Start a Project</div><h2>Butuh solusi Electrical, Renewable Energy atau Telecom?</h2><p style={{color:'#c9d4e2'}}>Konsultasikan kebutuhan proyek Anda dengan JPN.</p><Link className="btn" href="/kontak/">Konsultasi Sekarang</Link></div></section>
</>}
