import {notFound} from 'next/navigation';import type {Metadata} from 'next';import Link from 'next/link';import {services,faqs} from '@/data/site';
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return s?{title:`${s.title} | JPN`,description:`Layanan ${s.title} CV. Jaya Prima Nusantara untuk kebutuhan bisnis, industri, commercial dan hunian.`}:{title:'Layanan JPN'}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();return <>
<section className="hero"><div className="breadcrumb">Home / Services / {s.title}</div><div className="eyebrow">JPN SERVICE</div><h1>{s.title}</h1><p>{s.description}</p></section>
<section className="section"><div className="grid"><div><img className="visual" src={s.visual} alt={`${s.title} JPN`}/></div><div><div className="eyebrow">Scope of Work</div><h2>What we can support.</h2><ul className="serviceItems">{s.items.map(i=><li key={i}>{i}</li>)}</ul></div></div></section>
<section className="section" style={{background:'#f7f9fc'}}><div className="sectionHead"><div className="eyebrow">Process</div><h2>Structured technical execution.</h2></div><div className="process">{['Assessment','Planning & Proposal','Execution','Testing & Handover'].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3><p className="muted">Tahap pekerjaan disesuaikan dengan scope dan kebutuhan proyek.</p></div>)}</div></section>
<section className="section"><div className="sectionHead"><div className="eyebrow">FAQ</div><h2>Frequently Asked Questions</h2></div>{faqs.slice(0,5).map(([q,a])=><details className="card" style={{marginBottom:10}} key={q}><summary><b>{q}</b></summary><p className="muted">{a}</p></details>)}</section>
<section className="section" style={{background:'#071526',color:'#fff'}}><div className="sectionHead"><div className="eyebrow">Project Inquiry</div><h2>Butuh solusi {s.title}?</h2><p style={{color:'#c9d4e2'}}>Sampaikan kebutuhan Anda dan tim JPN dapat membahas scope proyek lebih lanjut.</p><Link className="btn" href="/kontak/">Konsultasi Sekarang</Link></div></section>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Service','name':s.title,'provider':{'@type':'Organization','name':'CV. Jaya Prima Nusantara'},'areaServed':'Jabodetabek'})}}/>
</>}
